config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root
  authenticated :user do
    root to: redirect('home'), as: :root_home
    get :home, to: 'home#index', as: :home
  end
  root to: 'welcome#index', as: :welcome

  # Devise routes
  devise_for :users,
             controllers:
             {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'

             }

  # Concerns
  concern :commentable do
    resources :comments, only: %i[index create destroy], concerns: :likeable
  end

  concern :likeable do
    resources :likes, only: %i[index create destroy]
  end

  # Users and nested resources
  resources :users, only: %i[show] do
    resources :status_updates, shallow: true, concerns: %i[commentable likeable]
    resource :profile, only: %i[edit update]
    post :set_avatar, to: 'profiles#set_avatar'
    post :set_cover, to: 'profiles#set_cover'
    resources :friendships, only: %i[index create update destroy]
    resources :photo_albums do
      resources :images, except: :new,
                         shallow: true,
                         concerns: %i[commentable likeable]
    end
  end

  # Notifications
  resources :notifications, only: :index do
    post 'mark_as_read', on: :collection
    post 'clear', on: :collection
  end

  # Autocomplete & Search
  get :autocomplete, to: 'autocomplete#index'

  namespace :autocomplete do
    get :friends
  end

  namespace :search do
    get :users, :status_updates, :images, :comments
  end

  # Email check
  get :check_email, to: 'users#check_email'

  # Conversations and messages
  resources :conversations, except: %i[edit create update] do
    get :unread_count, on: :collection
  end
  resources :messages, only: %i[create]
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :set_search_term

  CATEGORIES = {
    'Users' => [User, :name, [:profile]],
    'Status updates' => [StatusUpdate, :text, [:author]],
    'Comments' => [Comment, :text, %i[commentable author]],
    'Images' => [Image, :description, [:author]]
  }.freeze

  def users
    @resources = Search::CategorySearch.search(CATEGORIES['Users'], params)
  end

  def status_updates
    @resources = Search::CategorySearch.search(CATEGORIES['Status updates'], params)
  end

  def images
    @resources = Search::CategorySearch.search(CATEGORIES['Images'], params)
  end

  def comments
    @resources = Search::CategorySearch.search(CATEGORIES['Comments'], params)
  end

  private

  def set_search_term
    @search_term = params[:q]
  end
end

app/views/search/_menu.html.haml
.row
  .column
    .ui.blue.raised.attached.segment
      %h2.ui.header
        %i.search.teal.icon
        .content
          = "Results for '#{@search_term}'"

    .ui.bottom.attached.pointing.raised.four.item.teal.menu
      // Users
      = link_to search_users_path(q: @search_term),
        class: class_string('item', 'active' => current_page?(search_users_path)) do
        %i.users.icon
        Users

      // Status updates
      = link_to search_status_updates_path(q: @search_term),
        class: class_string('item', 'active' => current_page?(search_status_updates_path)) do
        %i.newspaper.icon
        Status updates

      // Images
      = link_to search_images_path(q: @search_term),
        class: class_string('item', 'active' => current_page?(search_images_path)) do
        %i.image.icon
        Images

      // Comments
      = link_to search_comments_path(q: @search_term),
        class: class_string('item', 'active' => current_page?(search_comments_path)) do
        %i.comments.icon
        Comments

app/views/search/comments.html.haml
= provide :title, "Search | Comments"

= render 'menu'

- if !@resources.blank?
  .row
    .sixteen.wide.column
      .ui.left.aligned.stackable.grid
        - @resources.each do |resource|
          .eight.wide.column
            .ui.segment
              .ui.divided.link.items
                = link_to url_for(resource.commentable), class: 'item' do
                  .ui.tiny.image
                    = image_tag resource.commentable.author.avatar.url(:thumb)
                  .content
                    .header= resource.author_name
                    .description= resource.text.truncate(130) || ''
  .row
    = paginate @resources

- else
  .ui.blue.message
    %h3.header No comments

app/views/search/images.html.haml
= provide :title, "Search | Images"

= render 'menu'

- if !@resources.blank?
  .row
    .sixteen.wide.column
      .ui.four.stackable.cards
        - @resources.each do |resource|
          = link_to image_path(resource), class: 'ui card' do
            .ui.rounded.fluid.image
              = image_tag resource.image.url(:mini)
  .row
    = paginate @resources

- else
  .ui.blue.message
    %h3.header No images

app/views/search/status_updates.html.haml
= provide :title, "Search | Status updates"

= render 'menu'

- if !@resources.blank?
  .row
    .sixteen.wide.column
      .ui.left.aligned.stackable.grid
        - @resources.each do |resource|
          .eight.wide.column
            .ui.segment
              .ui.divided.link.items
                = link_to status_update_path(resource), class: 'item' do
                  - if resource.image.url
                    .ui.tiny.image
                      = image_tag resource.image.url(:thumb)
                  .content
                    .header= resource.text.truncate(130)
                    .description= resource.author_name
  .row
    = paginate @resources

- else
  .ui.blue.message
    %h4.header No status updates

app/views/search/users.html.haml
= provide :title, "Search | Users"

= render 'menu'

- if !@resources.blank?
  .row
    .sixteen.wide.column
      .ui.four.stackable.cards
        - @resources.each do |resource|
          = render resource
  .row
    = paginate @resources

- else
  .ui.blue.message
    %h4.header No users