config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root
  authenticated :user do
    root to: redirect('home'), as: :root_home
    get :home, to: 'home#index', as: :home
  end
  root to: 'welcome#index', as: :welcome

  # Devise routes
  devise_for :users,
             controllers:
             {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'

             }

  # Concerns
  concern :commentable do
    resources :comments, only: %i[index create destroy], concerns: :likeable
  end

  concern :likeable do
    resources :likes, only: %i[index create destroy]
  end

  # Users and nested resources
  resources :users, only: %i[show] do
    resources :status_updates, shallow: true, concerns: %i[commentable likeable]
    resource :profile, only: %i[edit update]
    post :set_avatar, to: 'profiles#set_avatar'
    post :set_cover, to: 'profiles#set_cover'
    resources :friendships, only: %i[index create update destroy]
    resources :photo_albums do
      resources :images, except: :new,
                         shallow: true,
                         concerns: %i[commentable likeable]
    end
  end

  # Notifications
  resources :notifications, only: :index do
    post 'mark_as_read', on: :collection
    post 'clear', on: :collection
  end

  # Autocomplete & Search
  get :autocomplete, to: 'autocomplete#index'

  namespace :autocomplete do
    get :friends
  end

  namespace :search do
    get :users, :status_updates, :images, :comments
  end

  # Email check
  get :check_email, to: 'users#check_email'

  # Conversations and messages
  resources :conversations, except: %i[edit create update] do
    get :unread_count, on: :collection
  end
  resources :messages, only: %i[create]
end

app/models/status_update.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: status_updates
#
#  id             :integer          not null, primary key
#  author_id      :integer
#  text           :text
#  likes_count    :integer
#  comments_count :integer
#  image          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string           not null
#

class StatusUpdate < ApplicationRecord
  include Slug

  # Mount image uploader
  mount_uploader :image, StatusImageUploader

  # Associations
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :commenters, through: :comments, source: :author
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :notifications, as: :notifiable, dependent: :destroy

  # Validations
  validates_presence_of :author
  validates :text, length: { maximum: 4000, minimum: 1 }
  validate :text_or_image

  # Delegations
  delegate :name, to: :author, prefix: true

  # Search
  searchkick text_middle: %i[text],
             batch_size: 200,
             callbacks: :async

  # Scopes
  scope :search_import, -> { includes(:author) }
  scope :ordered, -> { order(created_at: :desc) }

  def search_info
    {
      title: text.truncate(60),
      image: image.url(:thumb) || '',
      url: Rails.application.routes.url_helpers.status_update_path(self),
      description: author_name
    }
  end

  private

  def text_or_image
    errors.add 'Please enter either some text or image or both.' if text.nil? && image.nil?
  end
end

app/controllers/status_updates_controller.rb
# frozen_string_literal: true

class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: %i[edit update destroy]

  def show
    @status_update = StatusUpdate.includes(author: :profile)
      .find_by_slug(params[:id])
  end

  def create
    @status_update = current_user.status_updates.build(status_update_params)
    authorize @status_update
    if @status_update.save
      flash[:success] = 'You\'ve posted an update.'
      send_notification(@status_update)
    else
      flash[:alert] = 'We were unable to save your status update.'
    end
    redirect_to request.referrer || current_user
  end

  def edit
    authorize @status_update
  end

  def update
    authorize @status_update
    if @status_update.update(status_update_params)
      flash[:success] = 'Status successfuly updated'
      redirect_to current_user
    else
      flash[:alert] = 'There was a problem updating your status. Try again?'
      render :edit
    end
  end

  def destroy
    authorize @status_update
    if @status_update.destroy
      flash[:success] = 'Your status update was destroyed'
    else
      flash[:alert] = 'There was a problem destroying your status update. Plese try again.'
    end
    redirect_to current_user
  end

  private

  def set_status_update
    @status_update = StatusUpdate.find_by_slug(params[:id])
  end

  def status_update_params
    params.require(:status_update).permit(:text, :image, :remote_image_url)
  end

  def send_notification(status_update)
    NotificationRelayJob.perform_later(status_update.author.friends.to_a,
                                       current_user,
                                       'posted',
                                       status_update)
  end
end

app/helpers/status_updates_helper.rb
# frozen_string_literal: true

module StatusUpdatesHelper
end

app/views/status_updates/_form.html.haml
.ui.clearing.segment
  .content
    = form_with model: (status_update.persisted? ? status_update : [current_user, status_update]),
      multipart: true,
      class: 'ui form',
      local: true do |form|

      .field
        = form.text_area :text,
          rows: 3,
          placeholder: 'What\'s on your mind today?',
          data: { 'behavior': 'su-form-link' }

      .actions{ style: 'display: none;'}
        .equal.width.fields
          .field
            = form.label :upload_image
            = form.file_field :image

          .field
            = form.label :image_from_url
            = form.text_field :remote_image_url, placeholder: 'Paste image url here...'

        = form.submit 'Post',
          class: 'ui blue right floated button'

        = link_to 'Cancel', nil,
          class: 'ui blue basic right floated button',
          data: { 'behavior': 'su-form-cancel-link' }

        - if status_update.persisted?

          = link_to 'Delete',
            status_update_path(status_update),
            method: 'delete',
            class: 'ui red basic right floated button',
            data: { 'confirm': 'Are you sure you want to delete it?' }

app/views/status_updates/_status_update.html.haml
.ui.fluid.card.commentable.lazy_image{ 'data-id': status_update.slug, 'data-type': status_update.class }

  // Status update's author's avatar, full name and date
  .content
    - if policy(status_update).edit?

      // Edit and delete buttons
      .ui.right.floated.meta

        = link_to 'Edit', edit_status_update_path(status_update),
                  class: 'ui blue label'

        = link_to 'Delete', status_update_path(status_update),
                  method: :delete,
                  data: { confirm: 'Are you sure' },
                  class: 'ui red label'

    // Author's avatar
    = link_to user_path(status_update.author) do
      = image_tag status_update.author.avatar.url(:thumb),
        class: 'ui left floated avatar image'

    // Author's name
    .header
      = link_to status_update.author.name, user_path(status_update.author)

    // Time at status_update creation
    .meta.time #{time_ago_in_words(status_update.created_at)} ago

  - unless status_update.text.empty?

    // Status update text
    .content
      .description.status_update__text.break-word
        = sanitize status_update.text,
          tags: %w[strong em a h3 h4 h5 h6 p hr ul ol li],
          attributes: ['href']

  - if status_update.image.url

    // Status update image
    .ui.centered.image
      = image_tag 'placeholder_status.jpg', data: { 'src': status_update.image.url(:normal) }

  -# Status update feedback actions/statistics
  = render 'shared/feedback_actions', feedbackable: status_update

app/views/status_updates/edit.html.haml
.ten.wide.centered.column
  = render 'status_updates/form', status_update: @status_update

-# Show status update image if it's present
-if @status_update.image.url
  .ten.wide.centered.column
    = image_tag @status_update.image.url(:normal), class: 'ui centered image'

app/views/status_updates/show.html.haml
.ten.wide.centered.column
  = render 'status_updates/status_update', status_update: @status_update